dist: trusty
language: c
env:
  - NGS_DIR=.
compiler:
  - gcc
  - clang
before_script:
  - sudo apt-get install -y uthash-dev libgc-dev libffi6 libffi-dev libjson-c2 libjson-c-dev peg gawk make libpcre3-dev
script:
  - cd c
  - make CC=$CC ngs
  - make test
